version: "3"

services:
  olhar180_taskliskui:
    build:
      context: .
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - /root/olhar180_tasklistui/dist:/app/dist
